"""Contains constant definitions"""
# from constants.wall_constants import MAZE_WIDTH

PLAYER_MOVEMENT_SPEED = 2

CHARACTER_SCALE = 1.0

WINDOW_WIDTH = 720
WINDOW_HEIGHT = 720

MAZE_WIDTH = 530 # includes the 20 pixels of tiles
MAZE_HEIGHT = 580 # includes the 20 pixels of tiles

H_DISTANCE_BETWEEN_EDGE_AND_MAZE = int((WINDOW_WIDTH - MAZE_WIDTH) / 2)

PIVOT_COL = [115, 160, 165, 225, 285, 325, 385, 425, 485, 545, 595]
PIVOT_ROW = [645, 575, 515, 385, 270, 210, 150, 90]

BLACK_BOX_WIDTH = 50
# BLACK_BOX_RATIO = 0.75 # ratio describes collision box / actual box size 
# BLACK_BOX_SIZE = BLACK_BOX_RATIO // 1
# COLLISION_BLACK_BOX_SIZE = (BLACK_BOX_RATIO * BLACK_BOX_SIZE) // 1
BLACK_BOX_DISTANCE = MAZE_WIDTH + BLACK_BOX_WIDTH 
BLACK_BOX_X_POSITION_1 = int(H_DISTANCE_BETWEEN_EDGE_AND_MAZE / 2)
COLLISION_BLACK_BOX_X_POSITIONS =[BLACK_BOX_X_POSITION_1 - int(BLACK_BOX_WIDTH / 2),
                        BLACK_BOX_X_POSITION_1 + BLACK_BOX_DISTANCE + 10 + BLACK_BOX_WIDTH]
LARGE_BLACK_BOX_X_POSITIONS =[BLACK_BOX_X_POSITION_1 - 6,
                        BLACK_BOX_X_POSITION_1 + BLACK_BOX_DISTANCE + int(BLACK_BOX_WIDTH / 2) + 18]

# COLLISION_BLACK_BOX_X_POSITIONS =[]
BLACK_BOX_Y_POSITION = int(WINDOW_HEIGHT / 2) + 30
COLLISION_BLACK_BOX_X_OFFSET_VAL = 1

SCREENWRAP_RIGHT_SIDE = 650
SCREENWRAP_LEFT_SIDE = 100

# BLACK_BOX_X_POS_RIGHT = 
# BLACK_BOX_X_POS_LEFT =
# BLACK_BOX_Y_POS = 