"""
Constants used for views (draw_text)
"""
from constants.constants import WINDOW_HEIGHT, WINDOW_WIDTH

LEVEL_DEFAULT_VALUE = 1

H1_FONT_SIZE = 48
H2_FONT_SIZE = 28
TEXT_FONT_NAMES = ('llpixel', 'arial')

H1_TEXT_Y_POS = WINDOW_HEIGHT-150

SCORE_IDX_COL_X_POS = WINDOW_WIDTH/4 + 60
INITIAL_COL_X_POS = WINDOW_WIDTH/2
HIGH_SCORE_COL_X_POS = 3*WINDOW_WIDTH/4

SCOREBOARD_ROW_DISTANCE = 30
SCOREBOARD_Y_OFFSET = 200