"""Contains constant definitions used for walls"""
from constants.constants import WINDOW_HEIGHT, WINDOW_WIDTH, MAZE_WIDTH, MAZE_HEIGHT, H_DISTANCE_BETWEEN_EDGE_AND_MAZE

TILE_WIDTH = 10
HALF_TILE_WIDTH = int(TILE_WIDTH / 2)
OUTER_VERTICAL_HEIGHT = 220
OUTER_HORIZONTAL_MINI = 110
OUTER_VERTICAL_MINI = 90
PATH_WIDTH = 40

# CENTER_X_POSITION = int(WINDOW_WIDTH / 2)
# CENTER_Y_POSITION = int(WINDOW_HEIGHT / 2)



MINI_HEIGHT = 20
MINIER_WIDTH = OUTER_HORIZONTAL_MINI - PATH_WIDTH
MINI_WIDTH = MINIER_WIDTH + TILE_WIDTH

HIGHEST_H_MINI_COMPONENT_Y_POS = OUTER_VERTICAL_MINI+PATH_WIDTH \
    + OUTER_VERTICAL_MINI + OUTER_VERTICAL_HEIGHT + int((WINDOW_HEIGHT \
    - MAZE_HEIGHT) / 2 - TILE_WIDTH * (3 / 2))
LOWEST_H_MINI_COMPONENT_Y_POS = OUTER_VERTICAL_HEIGHT \
    + int((WINDOW_HEIGHT - MAZE_HEIGHT) / 2 - TILE_WIDTH / 2)
SKINNY_BOX_Y_POSITION = 495 + PATH_WIDTH
H_MINI_COMPONENT_Y_POS_3RD_FROM_TOP = PATH_WIDTH \
    + OUTER_VERTICAL_MINI + OUTER_VERTICAL_HEIGHT + \
    int((WINDOW_HEIGHT - MAZE_HEIGHT) / 2 - TILE_WIDTH * (3 / 2))

LEFT_MINIER_BOX_X_POSITION = \
    int((WINDOW_WIDTH - MAZE_WIDTH) / 2 + OUTER_HORIZONTAL_MINI \
    - TILE_WIDTH / 2 + PATH_WIDTH)

SINGLE_UNIT_WIDTH = int(3 * TILE_WIDTH)
MIDDLE_T_H_WIDTH = SINGLE_UNIT_WIDTH + int(2 * PATH_WIDTH)
MIDDLE_T_X_POS = LEFT_MINIER_BOX_X_POSITION \
                    + SINGLE_UNIT_WIDTH + PATH_WIDTH - TILE_WIDTH
LOWER_MIDDLE_T_Y_POS = LOWEST_H_MINI_COMPONENT_Y_POS \
                    - 2 * PATH_WIDTH - TILE_WIDTH - SINGLE_UNIT_WIDTH

RIGHT_VERTICAL_X_POS = \
    WINDOW_WIDTH - H_DISTANCE_BETWEEN_EDGE_AND_MAZE \
    + int(TILE_WIDTH / 2) - PATH_WIDTH - MINI_WIDTH - MINIER_WIDTH
LEFT_VERTICAL_X_POS = \
    PATH_WIDTH + int((WINDOW_WIDTH - MAZE_WIDTH) / 2 \
    + OUTER_HORIZONTAL_MINI - TILE_WIDTH / 2)
CENTER_PIECE_X_POS = H_DISTANCE_BETWEEN_EDGE_AND_MAZE \
    + int (MAZE_WIDTH / 2) - (TILE_WIDTH * 2)

BOTTOM_BIT_Y_POS = LOWEST_H_MINI_COMPONENT_Y_POS \
                        - 2 * PATH_WIDTH - TILE_WIDTH - SINGLE_UNIT_WIDTH
LEFT_BOTTOM_BIT_X_POS = H_DISTANCE_BETWEEN_EDGE_AND_MAZE \
                    + 2 * TILE_WIDTH - MINI_WIDTH + PATH_WIDTH \
                    + TILE_WIDTH + TILE_WIDTH
RIGHT_BOTTOM_BIT_X_POS = WINDOW_WIDTH - H_DISTANCE_BETWEEN_EDGE_AND_MAZE \
                    - 2 * TILE_WIDTH - MINI_WIDTH + PATH_WIDTH

# bottom upside down T shapes
UPSIDE_DOWN_H_WIDTH = 2 * OUTER_VERTICAL_MINI - TILE_WIDTH
LEFT_UPSIDE_DOWN_Y_POS = LOWEST_H_MINI_COMPONENT_Y_POS - 2 * PATH_WIDTH \
                    - SINGLE_UNIT_WIDTH - OUTER_VERTICAL_MINI + 2 * TILE_WIDTH
LEFT_UPSIDE_DOWN_X_POS = LEFT_BOTTOM_BIT_X_POS + PATH_WIDTH
RIGHT_UPSIDE_DOWN_X_POS = LEFT_BOTTOM_BIT_X_POS + 3 * PATH_WIDTH \
                    + UPSIDE_DOWN_H_WIDTH + 2 * TILE_WIDTH

SPAWN_BOX_Y_POS = LOWEST_H_MINI_COMPONENT_Y_POS + 2 * TILE_WIDTH + PATH_WIDTH
SPAWN_BOX_HEIGHT = MIDDLE_T_H_WIDTH - 2 * TILE_WIDTH
SPAWN_BOX_MINI_WIDTH = MIDDLE_T_H_WIDTH - 2 * PATH_WIDTH
