"""Contains constant definitions"""

PLAYER_MOVEMENT_SPEED = 2
GRID_INCREMENT = 40
# allows for proper modulus calculations to stay on grid
MAGIC_NUMBER = 10

CHARACTER_SCALE = 0.75

WINDOW_WIDTH = 720
WINDOW_HEIGHT = 720

TILE_WIDTH = 10
MAZE_WIDTH = 530 # includes the 20 pixels of tiles
MAZE_HEIGHT = 580 # includes the 20 pixels of tiles
OUTER_VERTICAL_HEIGHT = 220
OUTER_HORIZONTAL_MINI = 110
OUTER_VERTICAL_MINI = 90
PATH_WIDTH = 40

CENTER_X_POSITION = int(WINDOW_WIDTH / 2)
CENTER_Y_POSITION = int(WINDOW_HEIGHT / 2)

PIVOT_COL = [115, 225, 325, 385, 425, 485, 595]
PIVOT_ROW = [645, 575, 515, 385]

H_DISTANCE_BETWEEN_EDGE_AND_MAZE = int((WINDOW_WIDTH - MAZE_WIDTH) / 2)

MINI_HEIGHT = 20
MINIER_WIDTH = OUTER_HORIZONTAL_MINI - PATH_WIDTH
MINI_WIDTH = MINIER_WIDTH + TILE_WIDTH
INNER_WIDTH = MAZE_WIDTH - 2 * (OUTER_HORIZONTAL_MINI)

HIGHEST_H_MINI_COMPONENT_Y_POS = OUTER_VERTICAL_MINI+PATH_WIDTH + OUTER_VERTICAL_MINI + OUTER_VERTICAL_HEIGHT + int((WINDOW_HEIGHT - MAZE_HEIGHT) / 2 - TILE_WIDTH * (3 / 2))
LOWEST_H_MINI_COMPONENT_Y_POS = OUTER_VERTICAL_HEIGHT + int((WINDOW_HEIGHT - MAZE_HEIGHT) / 2 - TILE_WIDTH / 2)
SKINNY_BOX_Y_POSITION = 495 + PATH_WIDTH

LEFT_MINIER_BOX_X_POSITION = int((WINDOW_WIDTH - MAZE_WIDTH) / 2 + OUTER_HORIZONTAL_MINI - TILE_WIDTH / 2 + PATH_WIDTH)

SINGLE_UNIT_WIDTH = int(3 * TILE_WIDTH)
MIDDLE_T_H_WIDTH = SINGLE_UNIT_WIDTH + int(2 * PATH_WIDTH)

RIGHT_VERTICAL_X_POS = WINDOW_WIDTH - H_DISTANCE_BETWEEN_EDGE_AND_MAZE + int(TILE_WIDTH / 2) - PATH_WIDTH - MINI_WIDTH - MINIER_WIDTH
LEFT_VERTICAL_X_POS = PATH_WIDTH + int((WINDOW_WIDTH - MAZE_WIDTH) / 2 + OUTER_HORIZONTAL_MINI - TILE_WIDTH / 2)
CENTER_PIECE_X_POS = H_DISTANCE_BETWEEN_EDGE_AND_MAZE + int (MAZE_WIDTH / 2) - (TILE_WIDTH * 2)